
import { Gym, Review } from './types';

export const MOCK_GYMS: Gym[] = [
  {
    id: 'g1',
    name: "Gold’s Gym Thrissur",
    location: 'Kuriachira, Thrissur',
    price: 2500,
    rating: 4.6,
    reviewCount: 840,
    photos: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800'],
    trainers: ['International Certified', 'Dieticians'],
    equipment: ['Life Fitness', 'Hammer Strength', 'Cardio Suite'],
    timings: '6:00 AM - 10:00 PM',
    isFeatured: true,
    tags: ['Premium', 'Kuriachira', 'Corporate Fitness'],
    description: 'Premier fitness destination with global standards. Contact: 08735973734'
  },
  {
    id: 'g2',
    name: 'Day Dome Fitness',
    location: 'East Fort Junction, Thrissur',
    price: 1200,
    rating: 4.4,
    reviewCount: 338,
    photos: ['https://images.unsplash.com/photo-1550345332-09e3ac987658?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Zumba Instructors', 'CrossFit Coaches'],
    equipment: ['Aerobics Floor', 'Multi-Gym', 'Free Weights'],
    timings: '6:00 AM - 10:00 PM',
    isFeatured: false,
    tags: ['East Fort', 'CrossFit', 'Zumba'],
    description: 'Vibrant club specializing in group classes and functional training. Contact: 08460475401'
  },
  {
    id: 'g3',
    name: 'White Rose Fitness & Wellness',
    location: 'Guruvayur, Thrissur',
    price: 1800,
    rating: 4.7,
    reviewCount: 156,
    photos: ['https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Wellness Coaches', 'Physiotherapists'],
    equipment: ['Modern Strength', 'Wellness Spa', 'Steam Room'],
    timings: '5:30 AM - 9:30 PM',
    isFeatured: false,
    tags: ['Guruvayur', 'Wellness', 'Clean'],
    description: 'Focus on holistic fitness and wellness in a pristine environment. Contact: 09054294311'
  },
  {
    id: 'g4',
    name: "Gold’s Gym Potta",
    location: 'Potta, Thrissur',
    price: 2200,
    rating: 4.8,
    reviewCount: 412,
    photos: ['https://images.unsplash.com/photo-1571902258032-78a9903a75a5?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Personal Trainers', 'Group Coaches'],
    equipment: ['State-of-the-art Strength', 'Cardio Section'],
    timings: '6:00 AM - 10:00 PM',
    isFeatured: true,
    tags: ['Potta', 'Premium', 'Corporate'],
    description: 'World-class gym facility serving the Potta area.'
  },
  {
    id: 'g5',
    name: 'Muscle Point Fitness Centre',
    location: 'Thiroor, Thrissur',
    price: 1000,
    rating: 5.0,
    reviewCount: 92,
    photos: ['https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Bodybuilding Experts'],
    equipment: ['Hardcore Iron', 'Power Racks'],
    timings: '6:00 AM - 9:00 PM',
    isFeatured: false,
    tags: ['Thiroor', 'Hardcore', 'Bodybuilding'],
    description: 'Top-rated destination for serious lifters and strength athletes. Contact: +91 72932 87026'
  },
  {
    id: 'g6',
    name: 'Regency Club',
    location: 'Kuttanellur, Thrissur',
    price: 2000,
    rating: 4.0,
    reviewCount: 215,
    photos: ['https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Swim Coaches', 'Gym Instructors'],
    equipment: ['Swimming Pool', 'Basic Gym', 'Tennis Courts'],
    timings: '6:00 AM - 9:00 PM',
    isFeatured: false,
    tags: ['Kuttanellur', 'Pool', 'Club'],
    description: 'Complete sports and fitness complex with a swimming pool. Contact: +91 487 235 3101'
  },
  {
    id: 'g7',
    name: 'Aquatics Complex',
    location: 'Patturaikkal, Thrissur',
    price: 1500,
    rating: 4.0,
    reviewCount: 180,
    photos: ['https://images.unsplash.com/photo-1593079831268-3381b0db4a77?auto=format&fit=crop&q=80&w=800'],
    trainers: ['General Trainers'],
    equipment: ['Pool Access', 'Weight Room'],
    timings: '6:00 AM - 8:30 PM',
    isFeatured: false,
    tags: ['Patturaikkal', 'Pool', 'Government'],
    description: 'Public aquatic and fitness facility. Contact: +91 97905 01936'
  },
  {
    id: 'g8',
    name: 'Elite Fitness Studio',
    location: 'Thrissur City',
    price: 2400,
    rating: 4.7,
    reviewCount: 210,
    photos: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Certified Professionals'],
    equipment: ['Premium Cardio', 'Selected Strength'],
    timings: '6:00 AM - 10:00 PM',
    isFeatured: true,
    tags: ['City Center', 'Premium', 'Modern'],
    description: 'High-end studio with modern equipment and certified coaching.'
  },
  {
    id: 'g9',
    name: 'Iron House Gym',
    location: 'Thrissur Central',
    price: 1100,
    rating: 4.3,
    reviewCount: 145,
    photos: ['https://images.unsplash.com/photo-1534367507873-d2d7e249a152?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Weightlifting Coaches'],
    equipment: ['CrossFit Rig', 'Bumper Plates', 'Dumbbells'],
    timings: '5:00 AM - 11:00 PM',
    isFeatured: false,
    tags: ['Central', 'CrossFit', 'Weightlifting'],
    description: 'Rugged environment perfect for CrossFit and heavy lifting.'
  },
  {
    id: 'g10',
    name: 'Phoenix Fitness Studio',
    location: 'Thrissur West',
    price: 1650,
    rating: 4.6,
    reviewCount: 198,
    photos: ['https://images.unsplash.com/photo-1594882645126-14020914d58d?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Yoga Instructors', 'Functional Coaches'],
    equipment: ['TRX', 'Kettlebells', 'Yoga Studio'],
    timings: '6:00 AM - 9:00 PM',
    isFeatured: false,
    tags: ['West', 'Yoga', 'Functional'],
    description: 'Multi-disciplinary studio offering Yoga and Functional training.'
  },
  {
    id: 'g11',
    name: 'EverShine Fitness',
    location: 'West Fort, Thrissur',
    price: 900,
    rating: 4.2,
    reviewCount: 88,
    photos: ['https://images.unsplash.com/photo-1581009146145-b5ef03a94e77?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Weight Loss Specialists'],
    equipment: ['Treadmills', 'Multi-Gym', 'Dumbbells'],
    timings: '6:00 AM - 9:30 PM',
    isFeatured: false,
    tags: ['West Fort', 'Weight Loss', 'Affordable'],
    description: 'Budget-friendly option focusing on weight loss and cardio.'
  },
  {
    id: 'g12',
    name: 'New Body Style Fitness Centre',
    location: 'Mannuthy, Thrissur',
    price: 1150,
    rating: 4.5,
    reviewCount: 112,
    photos: ['https://images.unsplash.com/photo-1570829463144-c701ccdd85e2?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Bodybuilding Coaches'],
    equipment: ['Standard Strength', 'Cardio Section'],
    timings: '6:00 AM - 10:00 PM',
    isFeatured: false,
    tags: ['Mannuthy', 'Bodybuilding'],
    description: 'Established gym in Mannuthy with a focus on hypertrophy.'
  },
  {
    id: 'g13',
    name: 'Bodyline Fitness Centre',
    location: 'Thrissur North',
    price: 1400,
    rating: 4.5,
    reviewCount: 245,
    photos: ['https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Personal Coaches'],
    equipment: ['Full Cardio Row', 'Hammer Strength'],
    timings: '6:00 AM - 10:00 PM',
    isFeatured: false,
    tags: ['North', 'Personal Coaching'],
    description: 'Professional gym with a strong emphasis on personal results. Contact: +91 94470 12345'
  },
  {
    id: 'g14',
    name: 'Long Life Multi Gymnasium',
    location: 'Varandarappilly, Thrissur',
    price: 800,
    rating: 4.1,
    reviewCount: 65,
    photos: ['https://images.unsplash.com/photo-1517838276556-c1075d013753?auto=format&fit=crop&q=80&w=800'],
    trainers: ['General Coaches'],
    equipment: ['Multi-Gym Setup', 'Weight Training'],
    timings: '6:00 AM - 9:00 PM',
    isFeatured: false,
    tags: ['Varandarappilly', 'Budget Friendly'],
    description: 'Traditional multi-gym catering to the local community.'
  },
  {
    id: 'g15',
    name: 'Max Fitness Club',
    location: 'Thrissur South',
    price: 1600,
    rating: 4.5,
    reviewCount: 178,
    photos: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Certified Trainers', 'Yoga Coaches'],
    equipment: ['Air Conditioned', 'Modern Cardio'],
    timings: '6:00 AM - 11:00 PM',
    isFeatured: false,
    tags: ['South', 'Classes', 'Late Hours'],
    description: 'Modern club with great group class options.'
  },
  {
    id: 'g16',
    name: 'Infinity Fitness Studio',
    location: 'Thrissur East',
    price: 2600,
    rating: 4.7,
    reviewCount: 145,
    photos: ['https://images.unsplash.com/photo-1550259979-ed79b48d2a30?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Elite Coaches', 'Nutritionists'],
    equipment: ['Panatta Strength', 'Real-time Tracking'],
    timings: '24/7 Access',
    isFeatured: true,
    tags: ['East', 'Premium', '24/7'],
    description: 'High-end 24/7 facility with premium European equipment.'
  },
  {
    id: 'g17',
    name: 'Spartan Gym',
    location: 'Thrissur West',
    price: 1250,
    rating: 4.6,
    reviewCount: 122,
    photos: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=800'],
    trainers: ['S&C Coaches'],
    equipment: ['CrossFit Rig', 'Lifting Platforms'],
    timings: '6:00 AM - 10:00 PM',
    isFeatured: false,
    tags: ['West', 'CrossFit', 'Strength'],
    description: 'Functional strength training focused gym.'
  },
  {
    id: 'g18',
    name: 'Victory Fitness Studio',
    location: 'Thrissur Central',
    price: 1950,
    rating: 4.6,
    reviewCount: 167,
    photos: ['https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Certified Lead Coach'],
    equipment: ['Imported Machines', 'Recovery Zone'],
    timings: '6:00 AM - 10:00 PM',
    isFeatured: false,
    tags: ['Central', 'Premium', 'Modern'],
    description: 'Premium boutique studio with high-end recovery options.'
  },
  {
    id: 'g19',
    name: 'Titanium Fitness Club',
    location: 'Thrissur South',
    price: 1450,
    rating: 4.5,
    reviewCount: 89,
    photos: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800'],
    trainers: ['Personal Trainers'],
    equipment: ['Modern Strength', 'Cycle Studio'],
    timings: '6:00 AM - 9:30 PM',
    isFeatured: false,
    tags: ['South', 'Modern'],
    description: 'Sleek modern club with personal training focus.'
  },
  {
    id: 'g20',
    name: 'Champion’s Gym',
    location: 'Thrissur City Area',
    price: 950,
    rating: 4.1,
    reviewCount: 134,
    photos: ['https://images.unsplash.com/photo-1517838276556-c1075d013753?auto=format&fit=crop&q=80&w=800'],
    trainers: ['General Fitness Staff'],
    equipment: ['Free Weights', 'Cardio Basics'],
    timings: '6:00 AM - 9:00 PM',
    isFeatured: false,
    tags: ['City Area', 'Affordable', 'Basics'],
    description: 'Solid entry-level gym with all the essentials.'
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    userName: 'Rahul Nair',
    userImage: 'https://i.pravatar.cc/150?u=rahul',
    rating: 5,
    comment: 'Best equipment in Thrissur. The trainers at Gold\'s Gym really know their stuff!',
    date: '2 days ago'
  },
  {
    id: 'r2',
    userName: 'Anjali Menon',
    userImage: 'https://i.pravatar.cc/150?u=anjali',
    rating: 5,
    comment: 'Muscle Point is amazing for serious lifters. Perfect 5.0 for a reason!',
    date: '1 week ago'
  }
];
